### ISSUE TITLE
gui: audit and update the list of required dependencies

### ISSUE THREAD

**Issue by edouardparis** [revault/liana#105]
we need to update the list of dependencies in the GUI README
There is no dummysigner
And we should differentiate between build and runtime dependencies

**Comment by darosior** [comment]
This was partially addressed in #124. We still need to draw a line between what we need in our reproducible build toolchain for distributing binaries, and what the user will be required to have on their machine to run this binary.

**Comment by darosior** [comment]
From my work on reproducible builds (see #140) here is a list of dependencies for the GUI.

Build-time dependencies:
- [`cargo`](github.com/rust-lang/cargo/) (>= 1.60.0 if patched, >= 1.62.0 otherwise)
- [`coreutils`](https://www.gnu.org/software/coreutils/coreutils.html) (Not even sure if it is required to build as such)
- [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/)
- [`libudev`](https://www.freedesktop.org/software/systemd/man/libudev.html) (We use [`eudev`](https://wiki.gentoo.org/wiki/Project:Eudev))
- [`fontconfig`](https://www.freedesktop.org/wiki/Software/fontconfig/)

Runtime dependencies:


```
$ ldd /tmp/tmp.3PVemFlaj8/out/gui/release/liana-gui
	linux-vdso.so.1 (0x00007ffda613e000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007ff823c48000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ff822536000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007ff823c00000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff823bfb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff823bdb000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff823bd4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff823bcf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff822457000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff822276000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff823c9a000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ff822240000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff823bb2000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007ff822231000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ff822206000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ff8221fc000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007ff8221d9000)
```

**Comment by darosior** [comment]
Yet another update: as far as i can tell what is listed in https://github.com/revault/liana/blob/master/doc/TRY.md#system-dependencies is sufficient for runtime dependencies (fontconfig and libudev).

**Comment by darosior** [comment]
Alright, i'm taking care of this.
